spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  application:
    name: kafka-producer

server:
  port: 8081

logging:
  level:
    com.example.producer: INFO
    org.springframework.kafka: INFO